# 1. Use official Nginx image
FROM nginx:latest

# 2. Create a non-root user
RUN useradd -u 1000 -m nginxuser

# 3. Copy your simplified config
COPY nginx.conf /etc/nginx/nginx.conf

# 4. Copy website files
COPY html/ /usr/share/nginx/html/

# 5. Create required dirs for nginx and own it for non root user
RUN mkdir -p /var/cache/nginx \
    && chown -R 1000:1000 /var/cache/nginx
RUN mkdir -p /run \
    && chown -R 1000:1000 /run

# 6. Change ownership to non-root user
RUN chown -R 1000:1000 /usr/share/nginx/html

# 7. Switch to non-root user
USER 1000

# 8. Expose the port your config listens on
EXPOSE 8080

# 9. Start nginx
CMD ["nginx", "-g", "daemon off;"]
